### ISSUE TITLE
ERROR: crypt() returned null with 4-line file

### ISSUE THREAD

**Issue by Terf** [Washington-University/HCPpipelines#209]
I'm trying to run the HCP pipelines (via the [BIDS app](https://github.com/BIDS-Apps/HCPPipelines)):
```
singularity run -e \
    -B $PWD/nifti:/bids_dataset:ro \
    -B $PWD/hcppipelines/sub-${sub}:/output \
    $PWD/simg/hcppipelines_latest.sif \
    /bids_dataset /output participant --participant_label $sub \
    --n_cpus 1 --processing-mode legacy --license_key "XXXXX"
```

but it's erroring out with an odd message: `ERROR: crypt() returned null with 4-line file`. Does anyone have any idea what that error could indicate? Below is the full output, written to `/output/sub-01/T1w/sub-01/scripts/recon-all.log`

```
[...]
Wed Mar  7 02:21:28 EST 2021:PreFreeSurferPipeline.sh: Completed!

FreeSurfer in LegacyStyleData mode
/opt/HCP-Pipelines/FreeSurfer/FreeSurferPipeline.sh --subject="sub-01" --subjectDIR="/output/sub-01/T1w" --t1="/output/sub-01/T1w/T1w_acpc_dc_restore.nii.gz" --t1brain
="/output/sub-01/T1w/T1w_acpc_dc_restore_brain.nii.gz" --processing-mode="LegacyStyleData"
========================================
  DIRECTORY: /opt/HCP-Pipelines  
    PRODUCT: HCP Pipeline Scripts
    VERSION: v4.1.3
========================================
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: HCPPIPEDIR: /opt/HCP-Pipelines
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: FREESURFER_HOME: /opt/freesurfer
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Platform Information Follows:
Linux pennsive01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: We were not able to locate one of the following required tools:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: recon-all.v6.hires, conf2hires, or longmc
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: To be able to run this script using the standard versions of these tools,
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: we added /opt/HCP-Pipelines/FreeSurfer/custom to the beginning of the PATH.
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: If you intended to use some other version of these tools, please configure
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: your PATH before invoking this script, such that the tools you intended to
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: use can be found on the PATH.
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: WARNING: PATH set to: /opt/HCP-Pipelines/FreeSurfer/custom:/usr/local/fsl/bin:/usr/local/miniconda/bin:/opt/freesur
fer/bin:/opt/freesurfer/fsfast/bin:/opt/freesurfer/tktools:/opt/freesurfer/mni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Showing HCP Pipelines version
========================================
  DIRECTORY: /opt/HCP-Pipelines  
    PRODUCT: HCP Pipeline Scripts
    VERSION: v4.1.3
========================================
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Showing recon-all.v6.hires version
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: /opt/HCP-Pipelines/FreeSurfer/custom/recon-all.v6.hires
freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Showing tkregister version
/opt/freesurfer/tktools/tkregister
stable6
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Showing mri_concatenate_lta version
/opt/freesurfer/bin/mri_concatenate_lta
stable6
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Showing mri_surf2surf version
/opt/freesurfer/bin/mri_surf2surf
stable6
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Showing fslmaths location
/usr/local/fsl/bin/fslmaths
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: INFO: Determined that FreeSurfer full version string is: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: INFO: Determined that FreeSurfer version is: 6.0.1
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Using named parameters
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: LegacyStyleData mode requested.
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: NOTICE: You are using a mode that enables processing of acquisitions that do not
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:         conform to the HCP specification as described in Glasser et al. (2013)!
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:         Be aware that if the HCP requirements are not met, the level of data quality
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:         can not be guaranteed and the Glasser et al. (2013) paper should not be used
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:         in support of this workflow. A manuscript with comprehensive evaluation for
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:         the LegacyStyleData processing mode is in active preparation and should be
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:         appropriately cited when published.
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: The following LegacyStyleData settings were requested: --t2w-image= or --t2= not present or set to NONE
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Subject Directory: /output/sub-01/T1w
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Subject: sub-01
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: T1w Image: /output/sub-01/T1w/T1w_acpc_dc_restore.nii.gz
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: T1w Brain: /output/sub-01/T1w/T1w_acpc_dc_restore_brain.nii.gz
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Include -conf2hires flag in recon-all: TRUE
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: ProcessingMode: LegacyStyleData
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Starting main functionality
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Retrieve positional parameters
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: SubjectDIR: /output/sub-01/T1w
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: SubjectID: sub-01
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: T1wImage: /output/sub-01/T1w/T1w_acpc_dc_restore.nii.gz
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: T1wImageBrain: /output/sub-01/T1w/T1w_acpc_dc_restore_brain.nii.gz
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: T2wImage: NONE
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: recon_all_seed:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: flair: FALSE
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: existing_subject: FALSE
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: extra_reconall_args:
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: conf2hires: TRUE
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Figure out the number of cores to use.
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: num_cores: 1
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: Thresholding T1w image to eliminate negative voxel values
Wed Mar  7 02:21:33 EST 2021:FreeSurferPipeline.sh: ...This produces a new file named: /output/sub-01/T1w/T1w_acpc_dc_restore_zero_threshold.nii.gz
Wed Mar  7 02:21:34 EST 2021:FreeSurferPipeline.sh: Call custom recon-all: recon-all.v6.hires
Wed Mar  7 02:21:34 EST 2021:FreeSurferPipeline.sh: ...recon_all_cmd: recon-all.v6.hires -subjid sub-01 -sd /output/sub-01/T1w -all -i /output/sub-01/T1w/T1w_acpc_dc_r
estore_zero_threshold.nii.gz -emregmask /output/sub-01/T1w/T1w_acpc_dc_restore_brain.nii.gz -openmp 1 -conf2hires
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /output/sub-01/T1w
Actual FREESURFER_HOME /opt/freesurfer
Linux pennsive01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
'/opt/HCP-Pipelines/FreeSurfer/custom/recon-all.v6.hires' -> '/output/sub-01/T1w/sub-01/scripts/recon-all.local-copy'
/output/sub-01/T1w/sub-01

 mri_convert /output/sub-01/T1w/T1w_acpc_dc_restore_zero_threshold.nii.gz /output/sub-01/T1w/sub-01/mri/orig/001.mgz

mri_convert.bin /output/sub-01/T1w/T1w_acpc_dc_restore_zero_threshold.nii.gz /output/sub-01/T1w/sub-01/mri/orig/001.mgz
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /output/sub-01/T1w/T1w_acpc_dc_restore_zero_threshold.nii.gz...
ERROR: crypt() returned null with 4-line file
Linux pennsive01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-01 exited with ERRORS at Wed Mar  7 02:21:37 EST 2021

For more details, see the log file /output/sub-01/T1w/sub-01/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Wed Mar  7 02:21:37 EST 2021:FreeSurferPipeline.sh: While running '/opt/HCP-Pipelines/FreeSurfer/FreeSurferPipeline.sh --subject=sub-01 --subjectDIR=/output/sub-01/T1w
 --t1=/output/sub-01/T1w/T1w_acpc_dc_restore.nii.gz --t1brain=/output/sub-01/T1w/T1w_acpc_dc_restore_brain.nii.gz --processing-mode=LegacyStyleData':
Wed Mar  7 02:21:37 EST 2021:FreeSurferPipeline.sh: ERROR: recon-all command failed with return_code: 1
Wed Mar  7 02:21:37 EST 2021:FreeSurferPipeline.sh: ERROR: recon-all command failed with return_code: 1
Wed Mar  7 02:21:37 EST 2021:FreeSurferPipeline.sh: ABORTING

Traceback (most recent call last):
  File "/run.py", line 402, in <module>
    stage_func()
  File "/run.py", line 103, in run_freesurfer
    "OMP_NUM_THREADS": str(args["n_cpus"])})
  File "/run.py", line 31, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1
```

**Comment by glasserm** [comment]
Did you ask the folks who make the BIDS app about this?  That is not us.

**Comment by coalsont** [comment]
I would guess that this has something to do with freesurfer's validation of the license file, some searching suggests that they at least used to rely on a no longer supported behavior of that library function, so that version of freesurfer may be entirely nonfunctional with the system libraries in the container.  Again, something to raise with the BIDS App people, we can't really help here.
