### ISSUE TITLE
incompatible python versions

### ISSUE THREAD

**Issue by kristianeschenburg** [Washington-University/HCPpipelines#214]
Hi

I'm trying to walk through the PreFreeSurferPipeline.sh script.  I'm running into issues with respect to finding certain python functions.  Specifically, I receive the following error:

```bash
Traceback (most recent call last):
  File "/usr/local/fsl/6.0/bin/imcp", line 6, in <module>
    from fsl.scripts.imcp import main
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/fsl/scripts/imcp.py", line 26, in <module>
    import fsl.utils.imcp as imcp
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/fsl/utils/imcp.py", line 21, in <module>
    import nibabel        as nib
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/nibabel/analyze.py", line 87, in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/nibabel/volumeutils.py", line 22, in <module>
    from .casting import (shared_range, type_info, OK_FLOATS)
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/nibabel/casting.py", line 11, in <module>
    from .testing import setup_test  # noqa
  File "/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/nibabel/testing/__init__.py", line 21, in <module>
    from numpy.testing.decorators import skipif
ModuleNotFoundError: No module named 'numpy.testing.decorators'
```

Looking into the ```/usr/local/fsl/6.0/fslpython/envs/fslpython/lib/python3.7/site-packages/numpy/testing/``` I can find the ```skipif``` function in ```._private.decorators```.

Do you have any thoughts on what might be going on?

Thanks.

**Comment by coalsont** [comment]
Looks like the problem is in FSL.  This looks like the same error, with a suggested solution:

https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=FSL;a26a0779.2010
